# -*- coding: utf-8 -*-
"""Dashboard Streamlit_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BerPlDRZmE1nw9VUcDsLyOyDunwNQXG1
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import time
from textwrap import dedent

st.set_page_config(
    page_title="Solar GHI Forecasting Dashboard",
    layout="wide"
)

st.markdown(
    "<h1 style='text-align: center;'>☀️ Solar GHI Forecasting Dashboard</h1>",
    unsafe_allow_html=True
)

DATA_PATH = "Bias Correction_with_Day_Ahead_2hrahead_Forecast.csv"

@st.cache_data
def load_data():
    df = pd.read_csv(DATA_PATH)

    df["valid_time_ist"] = (
        pd.to_datetime(df["valid_time_ist"])
          .dt.tz_localize(None)
    )
    df["valid_time_ist"] = pd.to_datetime(df["valid_time_ist"])

    df = df.rename(columns={
        "avg_ghi": "GFS_GHI",
        "ALLSKY_SFC_SW_DWN": "Actual_GHI",
        "Day_Ahead_Forecast": "Daily_Forecast_GHI",
        "2hr_ahead_forecast": "Two_Hour_Ahead_Forecast"
    })

    df = df.sort_values("valid_time_ist").reset_index(drop=True)
    return df

df = load_data()

st.subheader("🏭 Plant & Forecast Configuration")

available_dates = sorted(df["valid_time_ist"].dt.date.unique())

c1, c2, c3, c4 = st.columns([1, 1.5, 1, 1])

with c1:
    state = st.selectbox(
        "State",
        ["Karnataka"]
    )

with c2:
    plant = st.selectbox(
        "Plant Name",
        ["Pavagada Solar Plant"]
    )

with c3:
    selected_date = st.date_input(
        "Date",
        value=available_dates[-1],
        min_value=available_dates[0],
        max_value=available_dates[-1]
    )

with c4:
    time_options = pd.date_range("06:30", "17:30", freq="1h").time

    selected_time = st.selectbox(
        "Time",
        options=time_options,
        format_func=lambda t: t.strftime("%H:%M")
    )


day_df = df[df["valid_time_ist"].dt.date == selected_date].copy()

day_df["hour"] = (
    day_df["valid_time_ist"].dt.hour +
    day_df["valid_time_ist"].dt.minute / 60
)

day_df = day_df[
    (day_df["hour"] >= 6.5) &
    (day_df["hour"] <= 17.5)
].copy()

selected_datetime = pd.to_datetime(
    str(selected_date) + " " + selected_time.strftime("%H:%M")
)

two_hour_end_time = selected_datetime + pd.Timedelta(hours=2)

target_row = day_df[
    day_df["valid_time_ist"] == two_hour_end_time
]

has_two_hour_forecast = (
    not target_row.empty and
    pd.notna(target_row["Two_Hour_Ahead_Forecast"].iloc[0])
)

if has_two_hour_forecast:
    two_hour_df = day_df[
        day_df["valid_time_ist"] <= two_hour_end_time
    ].copy()

    two_hour_df = two_hour_df.dropna(
        subset=["Two_Hour_Ahead_Forecast"]
    )
else:
    two_hour_df = pd.DataFrame()


if day_df.empty:
    st.warning("No data available for the selected date.")

else:
    st.success(f"Prediction available for {selected_date}")

    left_col, right_col = st.columns(2)

    ymax = max(
        day_df["Actual_GHI"].max(),
        day_df["GFS_GHI"].max(),
        day_df["Daily_Forecast_GHI"].max()
    )

    ymax = (int(ymax / 100) + 1) * 100

    tick_times = day_df["valid_time_ist"].dt.strftime("%H:%M").tolist()

    # =====================================================
    # FIRST ROW: DAILY FORECAST GHI ONLY
    # =====================================================

    GFS_COLOR = "#636EFA"
    TWO_HOUR_COLOR = "#76B7F2"
    
    fig1 = go.Figure()

    fig1.add_trace(go.Scatter(
        x=day_df["valid_time_ist"],
        y=day_df["Daily_Forecast_GHI"],
        mode="lines+markers",
        name="Daily Forecast GHI",
        line=dict(color="#F05A5A", width=2),
        marker=dict(color="#F05A5A"),
        fill="tozeroy",
        fillcolor="rgba(240, 90, 90, 0.25)"
    ))

    if has_two_hour_forecast:

        fig1.add_trace(go.Scatter(
            x=two_hour_df["valid_time_ist"],
            y=two_hour_df["Two_Hour_Ahead_Forecast"],
            mode="lines+markers",
            name="2-Hour Ahead Forecast",
            line=dict(color=TWO_HOUR_COLOR),
            marker=dict(color=TWO_HOUR_COLOR)
        ))

    else:
        pass

    fig1.update_layout(
        title="Daily Forecast GHI",
        xaxis_title="Time",
        yaxis_title="GHI",
        height=450,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        )
    )

    fig1.update_xaxes(
        tickmode="array",
        tickvals=day_df["valid_time_ist"],
        ticktext=tick_times
    )

    fig1.update_yaxes(range=[0, ymax])

    row1_col, row1_space = st.columns([4.5, 0.8])

    with row1_col:
        st.plotly_chart(fig1, use_container_width=True, key="daily_forecast_main")

    with row1_space:
        
        with st.container(border=True):
            
            st.markdown("### 📥 Export Forecast Data")

            download_cols = [
                "valid_time_ist",
                "Actual_GHI",
                "GFS_GHI",
                "Daily_Forecast_GHI",
                "Two_Hour_Ahead_Forecast"
            ]
    
            rename_download_cols = {
                "valid_time_ist": "Time",
                "Actual_GHI": "Actual GHI",
                "GFS_GHI": "GFS GHI",
                "Daily_Forecast_GHI": "Day Ahead Forecast GHI",
                "Two_Hour_Ahead_Forecast": "2-Hour Ahead Forecast GHI"
            }
    
            # =====================================================
            # DOWNLOAD 1: START OF DATA TO SELECTED DATE
            # =====================================================
    
            cumulative_download_df = df[
                df["valid_time_ist"].dt.date <= selected_date
            ].copy()
    
            cumulative_download_df["hour"] = (
                cumulative_download_df["valid_time_ist"].dt.hour
                + cumulative_download_df["valid_time_ist"].dt.minute / 60
            )
    
            cumulative_download_df = cumulative_download_df[
                (cumulative_download_df["hour"] >= 6.5)
                & (cumulative_download_df["hour"] <= 17.5)
            ].copy()
    
            cumulative_download_df = cumulative_download_df[
                download_cols
            ].rename(columns=rename_download_cols)
    
            cumulative_csv = cumulative_download_df.to_csv(
                index=False
            ).encode("utf-8")

    
            st.download_button(
                label="⬇️ Download data through selected date",
                data=cumulative_csv,
                file_name=f"forecast_data_through_{selected_date}.csv",
                mime="text/csv",
                use_container_width=True,
                key="download_cumulative_forecast"
            )
    
    
            # =====================================================
            # DOWNLOAD 2: SELECTED DATE ONLY
            # =====================================================
    
            day_download_df = day_df[
                download_cols
            ].copy().rename(columns=rename_download_cols)
    
            day_csv = day_download_df.to_csv(
                index=False
            ).encode("utf-8")
    
            st.download_button(
                label="⬇️ Download selected-day data",
                data=day_csv,
                file_name=f"forecast_data_{selected_date}.csv",
                mime="text/csv",
                use_container_width=True,
                key="download_selected_day_forecast"
            )

    # =====================================================
    # SECOND ROW: TWO PLOTS
    # LEFT: GFS VS DAILY FORECAST
    # RIGHT: DAILY FORECAST GHI ONLY
    # =====================================================

    left_col, right_col = st.columns(2)

    left_col, right_col = st.columns(2)

    with left_col:
        
        with st.container(border=True):
            
            st.markdown("### GFS vs Daily Forecast GHI")

            fig2 = go.Figure()
    
            fig2.add_trace(go.Scatter(
                x=day_df["valid_time_ist"],
                y=day_df["GFS_GHI"],
                mode="lines+markers",
                name="GFS GHI",
                line=dict(color=GFS_COLOR),
                marker=dict(color=GFS_COLOR)
            ))
    
            fig2.add_trace(go.Scatter(
                x=day_df["valid_time_ist"],
                y=day_df["Daily_Forecast_GHI"],
                mode="lines+markers",
                name="Daily Forecast GHI",
                line=dict(color="red"),
                marker=dict(color="red")
            ))
    
            fig2.update_layout(
                xaxis_title="Time",
                yaxis_title="GHI",
                height=430,
                margin=dict(l=20, r=20, t=45, b=20),
                legend=dict(
                    orientation="h",
                    yanchor="bottom",
                    y=1.02,
                    xanchor="right",
                    x=1
                )
            )
    
            fig2.update_xaxes(
                tickmode="array",
                tickvals=day_df["valid_time_ist"],
                ticktext=tick_times
            )
    
            fig2.update_yaxes(range=[0, ymax])
    
            st.plotly_chart(
                fig2,
                use_container_width=True,
                key="gfs_vs_daily_forecast"
            )
    
    
    with right_col:
        with st.container(border=True):
            st.markdown("### GFS vs 2-Hour Ahead Forecast")
    
            fig3 = go.Figure()
    
            if has_two_hour_forecast:
                fig3.add_trace(go.Scatter(
                    x=two_hour_df["valid_time_ist"],
                    y=two_hour_df["GFS_GHI"],
                    mode="lines+markers",
                    name="GFS GHI",
                    line=dict(color=GFS_COLOR),
                    marker=dict(color=GFS_COLOR)
                ))
    
                fig3.add_trace(go.Scatter(
                    x=two_hour_df["valid_time_ist"],
                    y=two_hour_df["Two_Hour_Ahead_Forecast"],
                    mode="lines+markers",
                    name="2-Hour Ahead Forecast",
                    line=dict(color=TWO_HOUR_COLOR),
                    marker=dict(color=TWO_HOUR_COLOR)
                ))
    
                fig3_tick_vals = two_hour_df["valid_time_ist"]
                fig3_tick_times = (
                    two_hour_df["valid_time_ist"]
                    .dt.strftime("%H:%M")
                    .tolist()
                )
    
            else:
                selected_target_time = two_hour_end_time.strftime("%H:%M")
    
                st.warning(
                    f"No 2-hour ahead forecast available on {selected_date} "
                    f"for selected time {selected_time.strftime('%H:%M')} "
                    f"(target time: {selected_target_time})"
                )
    
                fig3_tick_vals = day_df["valid_time_ist"]
                fig3_tick_times = (
                    day_df["valid_time_ist"]
                    .dt.strftime("%H:%M")
                    .tolist()
                )
    
            fig3.update_layout(
                xaxis_title="Time",
                yaxis_title="GHI",
                height=430,
                margin=dict(l=20, r=20, t=45, b=20),
                legend=dict(
                    orientation="h",
                    yanchor="bottom",
                    y=1.02,
                    xanchor="right",
                    x=1
                )
            )
    
            fig3.update_xaxes(
                tickmode="array",
                tickvals=fig3_tick_vals,
                ticktext=fig3_tick_times
            )
    
            fig3.update_yaxes(range=[0, ymax])
    
            st.plotly_chart(
                fig3,
                use_container_width=True,
                key="two_hour_gfs_comparison"
            )

    # =====================================================
    # PREVIOUS DAY COMPARISON PLOTS
    # =====================================================

    selected_date_only = pd.to_datetime(selected_date).date()
    previous_day = selected_date_only - pd.Timedelta(days=1)

    previous_df = df[
        df["valid_time_ist"].dt.date == previous_day
    ].copy()

    previous_df["hour"] = (
        previous_df["valid_time_ist"].dt.hour
        + previous_df["valid_time_ist"].dt.minute / 60
    )

    previous_df = previous_df[
        (previous_df["hour"] >= 6.5)
        & (previous_df["hour"] <= 17.5)
    ].copy()

    if previous_df.empty:
        st.warning(
            f"No previous-day data available for {previous_day}."
        )

    else:
        st.markdown(
            f"### 📈 Previous Day Performance Comparison ({previous_day})"
        )

        # Colours
        ACTUAL_COLOR = "#2E9D57"
        GFS_COLOR = "#636EFA"
        DAILY_FORECAST_COLOR = "red"
        TWO_HOUR_COLOR_PREVIOUS = "red"

        # Common y-axis maximum
        prev_ymax = max(
            previous_df["Actual_GHI"].max(),
            previous_df["GFS_GHI"].max(),
            previous_df["Daily_Forecast_GHI"].max(),
            previous_df["Two_Hour_Ahead_Forecast"].max(skipna=True)
        )

        prev_ymax = (int(prev_ymax / 100) + 1) * 100

        prev_tick_times = (
            previous_df["valid_time_ist"]
            .dt.strftime("%H:%M")
            .tolist()
        )

        prev_left, prev_right = st.columns(2)

        # =====================================================
        # PREVIOUS DAY LEFT PLOT
        # Actual + GFS + Daily Forecast
        # =====================================================

        with prev_left:
            with st.container(border=True):

                st.markdown(
                    "### Actual vs GFS vs Daily Forecast"
                )

                fig_prev1 = go.Figure()

                # Actual GHI — green dotted
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["Actual_GHI"],
                    mode="lines+markers",
                    name="Actual GHI",
                    line=dict(
                        color=ACTUAL_COLOR,
                        dash="dot"
                    ),
                    marker=dict(color=ACTUAL_COLOR)
                ))

                # GFS GHI — blue
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["GFS_GHI"],
                    mode="lines+markers",
                    name="GFS GHI",
                    line=dict(color=GFS_COLOR),
                    marker=dict(color=GFS_COLOR)
                ))

                # Daily Forecast — red
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["Daily_Forecast_GHI"],
                    mode="lines+markers",
                    name="Daily Forecast GHI",
                    line=dict(color=DAILY_FORECAST_COLOR),
                    marker=dict(color=DAILY_FORECAST_COLOR)
                ))

                fig_prev1.update_layout(
                    title=None,
                    xaxis_title="Time",
                    yaxis_title="GHI",
                    height=430,
                    margin=dict(
                        l=20,
                        r=20,
                        t=45,
                        b=20
                    ),
                    legend=dict(
                        orientation="h",
                        yanchor="bottom",
                        y=1.02,
                        xanchor="right",
                        x=1
                    )
                )

                fig_prev1.update_xaxes(
                    tickmode="array",
                    tickvals=previous_df["valid_time_ist"],
                    ticktext=prev_tick_times
                )

                fig_prev1.update_yaxes(
                    range=[0, prev_ymax]
                )

                st.plotly_chart(
                    fig_prev1,
                    use_container_width=True,
                    key="previous_day_actual_gfs_forecast"
                )

        # =====================================================
        # PREVIOUS DAY RIGHT PLOT
        # Actual + GFS + 2-Hour Ahead
        # =====================================================

        with prev_right:
            with st.container(border=True):

                st.markdown(
                    "### Actual vs GFS vs 2-Hour Ahead Forecast"
                )

                fig_prev2 = go.Figure()

                # Since the previous day is complete, use all rows
                # where 2-hour-ahead forecast exists.
                previous_two_hour_df = previous_df.dropna(
                    subset=["Two_Hour_Ahead_Forecast"]
                ).copy()

                if not previous_two_hour_df.empty:

                    # Actual GHI — green dotted
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df["Actual_GHI"],
                        mode="lines+markers",
                        name="Actual GHI",
                        line=dict(
                            color=ACTUAL_COLOR,
                            dash="dot"
                        ),
                        marker=dict(color=ACTUAL_COLOR)
                    ))

                    # GFS GHI — blue
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df["GFS_GHI"],
                        mode="lines+markers",
                        name="GFS GHI",
                        line=dict(color=GFS_COLOR),
                        marker=dict(color=GFS_COLOR)
                    ))

                    # 2-Hour Ahead Forecast — red
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df[
                            "Two_Hour_Ahead_Forecast"
                        ],
                        mode="lines+markers",
                        name="2-Hour Ahead Forecast",
                        line=dict(
                            color=TWO_HOUR_COLOR_PREVIOUS
                        ),
                        marker=dict(
                            color=TWO_HOUR_COLOR_PREVIOUS
                        )
                    ))

                    prev2_tick_vals = (
                        previous_two_hour_df["valid_time_ist"]
                    )

                    prev2_tick_text = (
                        previous_two_hour_df["valid_time_ist"]
                        .dt.strftime("%H:%M")
                        .tolist()
                    )

                else:
                    st.warning(
                        f"No previous-day 2-hour ahead forecast "
                        f"data available for {previous_day}."
                    )

                    prev2_tick_vals = previous_df["valid_time_ist"]

                    prev2_tick_text = (
                        previous_df["valid_time_ist"]
                        .dt.strftime("%H:%M")
                        .tolist()
                    )

                fig_prev2.update_layout(
                    title=None,
                    xaxis_title="Time",
                    yaxis_title="GHI",
                    height=430,
                    margin=dict(
                        l=20,
                        r=20,
                        t=45,
                        b=20
                    ),
                    legend=dict(
                        orientation="h",
                        yanchor="bottom",
                        y=1.02,
                        xanchor="right",
                        x=1
                    )
                )

                fig_prev2.update_xaxes(
                    tickmode="array",
                    tickvals=prev2_tick_vals,
                    ticktext=prev2_tick_text
                )

                fig_prev2.update_yaxes(
                    range=[0, prev_ymax]
                )

                st.plotly_chart(
                    fig_prev2,
                    use_container_width=True,
                    key="previous_day_two_hour_actual_gfs"
                )
    # =====================================================
    # CUMULATIVE ERROR METRICS: START DATE TO PREVIOUS DAY
    # =====================================================

    selected_date_only = pd.to_datetime(selected_date).date()
    previous_day = selected_date_only - pd.Timedelta(days=1)

    eval_df = df[
        df["valid_time_ist"].dt.date <= previous_day
    ].copy()

    eval_df = eval_df.dropna(
        subset=["Actual_GHI", "GFS_GHI", "Daily_Forecast_GHI"]
    )

    eval_df["hour"] = (
        eval_df["valid_time_ist"].dt.hour +
        eval_df["valid_time_ist"].dt.minute / 60
    )

    eval_df = eval_df[
        (eval_df["hour"] >= 6.5) &
        (eval_df["hour"] <= 17.5) &
        (eval_df["Actual_GHI"] > 50)
    ].copy()

    if not eval_df.empty:

        start_date = eval_df["valid_time_ist"].dt.date.min()
        end_date = eval_df["valid_time_ist"].dt.date.max()

        actual = eval_df["Actual_GHI"]
        before = eval_df["GFS_GHI"]
        after = eval_df["Daily_Forecast_GHI"]

        mae_before = (actual - before).abs().mean()
        mae_after = (actual - after).abs().mean()

        rmse_before = np.sqrt(((actual - before) ** 2).mean())
        rmse_after = np.sqrt(((actual - after) ** 2).mean())

        mape_before = ((actual - before).abs() / actual).mean() * 100
        mape_after = ((actual - after).abs() / actual).mean() * 100

        st.markdown(
            f"### 📊 Cumulative Performance of  Daily Forecast"
            f"({start_date} to {end_date})"
        )

        metric_col1, metric_col2, metric_col3 = st.columns(3)

        # ---------------- MAPE ----------------
        with metric_col1:
            fig_mape = go.Figure()

            fig_mape.add_trace(go.Bar(
                x=["Before", "After"],
                y=[mape_before, mape_after],
                text=[round(mape_before, 2), round(mape_after, 2)],
                textposition="auto",
                marker_color=["steelblue", "red"]
            ))

            fig_mape.update_layout(
                title="MAPE",
                xaxis_title="Model",
                yaxis_title="MAPE (%)",
                height=350
            )

            st.plotly_chart(
                fig_mape,
                use_container_width=True,
                key="mape_cumulative_chart"
            )

        # ---------------- MAE ----------------
        with metric_col2:
            fig_mae = go.Figure()

            fig_mae.add_trace(go.Bar(
                x=["Before", "After"],
                y=[mae_before, mae_after],
                text=[round(mae_before, 2), round(mae_after, 2)],
                textposition="auto",
                marker_color=["steelblue", "red"]
            ))

            fig_mae.update_layout(
                title="MAE",
                xaxis_title="Model",
                yaxis_title="MAE",
                height=350
            )

            st.plotly_chart(
                fig_mae,
                use_container_width=True,
                key="mae_cumulative_chart"
            )

        # ---------------- RMSE ----------------
        with metric_col3:
            fig_rmse = go.Figure()

            fig_rmse.add_trace(go.Bar(
                x=["Before", "After"],
                y=[rmse_before, rmse_after],
                text=[round(rmse_before, 2), round(rmse_after, 2)],
                textposition="auto",
                marker_color=["steelblue", "red"]
            ))

            fig_rmse.update_layout(
                title="RMSE",
                xaxis_title="Model",
                yaxis_title="RMSE",
                height=350
            )

            st.plotly_chart(
                fig_rmse,
                use_container_width=True,
                key="rmse_cumulative_chart"
            )

    else:
        st.warning(
            "Not enough valid previous-day data to calculate cumulative forecast performance."
        )
        
    # =====================================================
    # OVERALL FULL-DATA PERFORMANCE METRICS
    # =====================================================

    overall_df = df.dropna(
        subset=[
            "Actual_GHI",
            "GFS_GHI",
            "Daily_Forecast_GHI"
        ]
    ).copy()

    overall_df["hour"] = (
        overall_df["valid_time_ist"].dt.hour
        + overall_df["valid_time_ist"].dt.minute / 60
    )

    overall_df = overall_df[
        (overall_df["hour"] >= 6.5)
        & (overall_df["hour"] <= 17.5)
        & (overall_df["Actual_GHI"] > 50)
    ].copy()

    if not overall_df.empty:

        # =====================================================
        # DAILY FORECAST METRICS
        # =====================================================

        actual_all = overall_df["Actual_GHI"]
        gfs_all = overall_df["GFS_GHI"]
        daily_all = overall_df["Daily_Forecast_GHI"]

        overall_mape_before = (
            ((actual_all - gfs_all).abs() / actual_all).mean() * 100
        )

        overall_mape_after = (
            ((actual_all - daily_all).abs() / actual_all).mean() * 100
        )

        overall_mae_before = (
            (actual_all - gfs_all).abs().mean()
        )

        overall_mae_after = (
            (actual_all - daily_all).abs().mean()
        )

        overall_rmse_before = np.sqrt(
            ((actual_all - gfs_all) ** 2).mean()
        )

        overall_rmse_after = np.sqrt(
            ((actual_all - daily_all) ** 2).mean()
        )

        st.markdown("## 📌 Performance Summary on Complete Dataset")

        left_summary, right_summary = st.columns(2)

        # =====================================================
        # LEFT: DAILY FORECAST PERFORMANCE
        # =====================================================

        with left_summary:

            with st.container(border=True):
                st.markdown(
                    "### 📈 Daily Forecast GHI: Overall Forecast Performance"
                )
                st.caption(
                    "Comparison of Original GFS and Daily Forecast GHI"
                )

            k1, k2, k3 = st.columns(3)

            # ---------------- MAPE ----------------
            with k1:
                with st.container(border=True):
                    st.markdown(
                        "<h3 style='color:#4c78d8;'>🎯 MAPE</h3>",
                        unsafe_allow_html=True
                    )

                    st.metric(
                        label="Before (GFS)",
                        value=f"{overall_mape_before:.2f}%"
                    )

                    st.markdown(
                        f"""
                        <div style="
                            color:#ff3b30;
                            font-size:2rem;
                            font-weight:700;
                            margin-top:-8px;
                        ">
                            {overall_mape_after:.2f}%
                        </div>
                        <div style="
                            font-size:0.9rem;
                            opacity:0.75;
                            margin-top:-4px;
                        ">
                            After (Daily Forecast)
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

            # ---------------- MAE ----------------
            with k2:
                with st.container(border=True):
                    st.markdown(
                        "<h3 style='color:#2e9d57;'>📊 MAE</h3>",
                        unsafe_allow_html=True
                    )

                    st.metric(
                        label="Before (GFS)",
                        value=f"{overall_mae_before:.2f}"
                    )

                    st.markdown(
                        f"""
                        <div style="
                            color:#ff3b30;
                            font-size:2rem;
                            font-weight:700;
                            margin-top:-8px;
                        ">
                            {overall_mae_after:.2f}
                        </div>
                        <div style="
                            font-size:0.9rem;
                            opacity:0.75;
                            margin-top:-4px;
                        ">
                            After (Daily Forecast)
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

            # ---------------- RMSE ----------------
            with k3:
                with st.container(border=True):
                    st.markdown(
                        "<h3 style='color:#8a4fd3;'>〽️ RMSE</h3>",
                        unsafe_allow_html=True
                    )

                    st.metric(
                        label="Before (GFS)",
                        value=f"{overall_rmse_before:.2f}"
                    )

                    st.markdown(
                        f"""
                        <div style="
                            color:#ff3b30;
                            font-size:2rem;
                            font-weight:700;
                            margin-top:-8px;
                        ">
                            {overall_rmse_after:.2f}
                        </div>
                        <div style="
                            font-size:0.9rem;
                            opacity:0.75;
                            margin-top:-4px;
                        ">
                            After (Daily Forecast)
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

        # =====================================================
        # RIGHT: 2-HOUR AHEAD PERFORMANCE
        # =====================================================

        with right_summary:

            two_hour_metrics_df = overall_df.dropna(
                subset=["Two_Hour_Ahead_Forecast"]
            ).copy()

            if not two_hour_metrics_df.empty:

                actual_2hr = two_hour_metrics_df["Actual_GHI"]
                gfs_2hr = two_hour_metrics_df["GFS_GHI"]
                daily_2hr = two_hour_metrics_df["Daily_Forecast_GHI"]
                forecast_2hr = two_hour_metrics_df[
                    "Two_Hour_Ahead_Forecast"
                ]

                # MAPE
                mape_gfs = (
                    ((actual_2hr - gfs_2hr).abs() / actual_2hr).mean()
                    * 100
                )

                mape_daily = (
                    ((actual_2hr - daily_2hr).abs() / actual_2hr).mean()
                    * 100
                )

                mape_2hr = (
                    ((actual_2hr - forecast_2hr).abs() / actual_2hr).mean()
                    * 100
                )

                # MAE
                mae_gfs = (
                    (actual_2hr - gfs_2hr).abs().mean()
                )

                mae_daily = (
                    (actual_2hr - daily_2hr).abs().mean()
                )

                mae_2hr = (
                    (actual_2hr - forecast_2hr).abs().mean()
                )

                # RMSE
                rmse_gfs = np.sqrt(
                    ((actual_2hr - gfs_2hr) ** 2).mean()
                )

                rmse_daily = np.sqrt(
                    ((actual_2hr - daily_2hr) ** 2).mean()
                )

                rmse_2hr = np.sqrt(
                    ((actual_2hr - forecast_2hr) ** 2).mean()
                )

                with st.container(border=True):
                    st.markdown(
                        "### 🕒 2-Hour Ahead Forecast: Overall Performance"
                    )
                    st.caption(
                        "Calculated only for rows where "
                        "2-Hour Ahead Forecast is available"
                    )

                h1, h2, h3 = st.columns(3)

                # ---------------- MAPE ----------------
                with h1:
                    with st.container(border=True):
                        st.markdown(
                            "<h3 style='color:#e66a00;'>🎯 MAPE</h3>",
                            unsafe_allow_html=True
                        )

                        st.metric(
                            label="Actual vs GFS",
                            value=f"{mape_gfs:.2f}%"
                        )

                        st.markdown(
                            f"""
                            <div style="
                                color:#2e9d57;
                                font-size:1.75rem;
                                font-weight:700;
                            ">
                                {mape_daily:.2f}%
                            </div>
                            <div style="
                                font-size:0.85rem;
                                opacity:0.75;
                                margin-bottom:16px;
                            ">
                                Actual vs Daily Forecast
                            </div>

                            <div style="
                                color:#e66a00;
                                font-size:1.75rem;
                                font-weight:700;
                            ">
                                {mape_2hr:.2f}%
                            </div>
                            <div style="
                                font-size:0.85rem;
                                opacity:0.75;
                            ">
                                Actual vs 2-Hour Ahead
                            </div>
                            """,
                            unsafe_allow_html=True
                        )

                # ---------------- MAE ----------------
                with h2:
                    with st.container(border=True):
                        st.markdown(
                            "<h3 style='color:#e66a00;'>📊 MAE</h3>",
                            unsafe_allow_html=True
                        )

                        st.metric(
                            label="Actual vs GFS",
                            value=f"{mae_gfs:.2f}"
                        )

                        st.markdown(
                            f"""
                            <div style="
                                color:#2e9d57;
                                font-size:1.75rem;
                                font-weight:700;
                            ">
                                {mae_daily:.2f}
                            </div>
                            <div style="
                                font-size:0.85rem;
                                opacity:0.75;
                                margin-bottom:16px;
                            ">
                                Actual vs Daily Forecast
                            </div>

                            <div style="
                                color:#e66a00;
                                font-size:1.75rem;
                                font-weight:700;
                            ">
                                {mae_2hr:.2f}
                            </div>
                            <div style="
                                font-size:0.85rem;
                                opacity:0.75;
                            ">
                                Actual vs 2-Hour Ahead
                            </div>
                            """,
                            unsafe_allow_html=True
                        )

                # ---------------- RMSE ----------------
                with h3:
                    with st.container(border=True):
                        st.markdown(
                            "<h3 style='color:#e66a00;'>〽️ RMSE</h3>",
                            unsafe_allow_html=True
                        )

                        st.metric(
                            label="Actual vs GFS",
                            value=f"{rmse_gfs:.2f}"
                        )

                        st.markdown(
                            f"""
                            <div style="
                                color:#2e9d57;
                                font-size:1.75rem;
                                font-weight:700;
                            ">
                                {rmse_daily:.2f}
                            </div>
                            <div style="
                                font-size:0.85rem;
                                opacity:0.75;
                                margin-bottom:16px;
                            ">
                                Actual vs Daily Forecast
                            </div>

                            <div style="
                                color:#e66a00;
                                font-size:1.75rem;
                                font-weight:700;
                            ">
                                {rmse_2hr:.2f}
                            </div>
                            <div style="
                                font-size:0.85rem;
                                opacity:0.75;
                            ">
                                Actual vs 2-Hour Ahead
                            </div>
                            """,
                            unsafe_allow_html=True
                        )

            else:
                st.warning(
                    "No valid 2-hour ahead forecast data is available "
                    "for overall performance."
                )

    else:
        st.warning(
            "Not enough valid data to calculate "
            "complete-dataset performance metrics."
        )
